/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Airplane: typeof import('./src/components/globe/Airplane.vue')['default']
    Cloud: typeof import('./src/components/globe/Cloud.vue')['default']
    EnemySpawner: typeof import('./src/components/enemies/EnemySpawner.vue')['default']
    Globe: typeof import('./src/components/globe/Globe.vue')['default']
    NulosModel: typeof import('./src/components/enemies/models/NulosModel.vue')['default']
    Planet: typeof import('./src/components/globe/Planet.vue')['default']
    Player: typeof import('./src/components/player/Player.vue')['default']
    PlayerModel: typeof import('./src/components/player/PlayerModel.vue')['default']
    Scene: typeof import('./src/components/Scene.vue')['default']
  }
}
